# Setup
title:               
tagline:             
description:
url:                 https://nilinykh.github.io
baseurl:             /
remote_theme:        poole/lanyon
permalink:           pretty


paginate: 5 # Default pagination for posts
paginate_path: "/blog/page:num"
pagination:
  enabled: true
  collections:
    posts:
      enabled: true
      per_page: 5
      permalink: "/blog/page:num"
    pages:
      enabled: true
      per_page: 5
      permalink: "/pages/page:num"



# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Gems
plugins:
  - jekyll-paginate-v2

# Custom vars
version:             
google_analytics_id: 
