# Setup
title:               
tagline:             
description:
url:                 https://nilinykh.github.io
baseurl:             /
remote_theme:        poole/lanyon
permalink:           pretty

collections:
  pages:
    output: true
  posts:
    output: true
paginate: 5 # The number of items per page
paginate_path: "/blog/page:num" # Path for posts pagination
# Add a custom paginator for pages
page_paginate: 5 # Number of pages per page
page_paginate_path: "/pages/page:num" # Path for pages pagination


# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             
google_analytics_id: 
